# Generated by Django 3.1.5 on 2021-01-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='sur_name',
        ),
    ]
